# ------------------------------------------------------------------------------
#  Copyright (C) 2026 Timothy H. Click
#
#  This file is part of mdscaffold.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------
"""Core business logic for mdscaffold.

This package contains all simulation pipeline logic for mdscaffold, organized into subpackages
by concern. It is strictly decoupled from the CLI layer (``mdscaffold.cli``) — no Typer, Rich,
or any other presentation-layer dependency appears here. Every public function and class in this
package is callable from a plain Python script or test without a CLI context.

The intended import boundary is::

    mdscaffold.cli  ->  mdscaffold.core  (allowed)
    mdscaffold.core ->  mdscaffold.cli  (never)

Subpackages
-----------
project
    Project configuration and directory layout. Defines ``ProjectConfig``, the top-level Pydantic
    model that is the single source of truth for a simulation project, alongside ``ProjectLayout``
    and ``StageLayout`` frozen dataclasses that encode the canonical directory structure. The
    ``scaffold`` module creates the directory tree on disk from a ``ProjectLayout`` instance.

simulation
    Typed representations of each simulation stage and the physical parameters that govern them.
    ``SimulationConfig`` (defined in ``project.config``) is parameterised by the models here.
    ``restraints`` encodes the tapered equilibration restraint schedule — six force constant steps
    and the Amber atom mask — as module-level constants consumed by the writers layer.

writers
    Jinja2-based file writers. Each module accepts a typed stage or config object and a destination
    ``Path``, renders the appropriate template from ``core/templates/``, and writes the result to
    disk. No side effects beyond the file write. Three sub-modules cover the three file categories
    generated by ``mdscaffold write``: Amber ``.in`` input scripts, SLURM/PBS/local job scripts,
    and ``README.md`` documentation stubs.

runners
    Scheduler-agnostic job submission and status checking. A ``Runner`` protocol in ``base``
    defines the interface; ``slurm``, ``pbs``, and ``local`` provide concrete implementations.
    The ``local`` runner executes jobs as blocking subprocesses, suitable for development and
    single-user workstations. The ``slurm`` runner wraps ``sbatch`` with dependency chaining
    via ``--dependency=afterok`` to enforce stage ordering across the pipeline.

analysis
    Trajectory analysis built on ``cpptraj``. The ``cpptraj`` module constructs and executes
    ``cpptraj`` input scripts; higher-level modules (``rmsd``, ``rmsf``, ``clustering``,
    ``contacts``) compose ``cpptraj`` commands for specific analyses and return structured results.

templates
    Jinja2 template files (``.j2``) for all generated file types. Organised into three
    subdirectories: ``amber/`` for ``.in`` input scripts, ``jobs/`` for scheduler job scripts,
    and ``readme/`` for ``README.md`` stubs. Templates are loaded at runtime via Jinja2's
    ``PackageLoader`` and are not imported as Python modules.

Notes
-----
**Dependency direction.** The subpackages have a strict internal dependency order::

    project  <-  simulation  <-  writers
                                runners
                                analysis

``project`` has no internal dependencies. ``simulation`` depends only on ``project``.
``writers``, ``runners``, and ``analysis`` may depend on both ``project`` and ``simulation``
but not on each other. Circular imports between subpackages are not permitted.

**No public re-exports.** This ``__init__.py`` intentionally does not re-export symbols from
subpackages. Callers should import directly from the relevant subpackage::

    # Preferred
    from mdscaffold.core.project.config import ProjectConfig
    from mdscaffold.core.simulation.stages import HeatStage

    # Avoid — fragile, hides provenance
    from mdscaffold.core import ProjectConfig

This keeps import paths explicit and makes refactoring across subpackages straightforward.

**Pydantic models vs dataclasses.** User-facing configuration objects that are constructed from
TOML files or CLI input (``ProjectConfig``, ``ReplicaConfig``, ``SimulationConfig``,
``SlurmConfig``) are Pydantic ``BaseModel`` subclasses with full validation. Internal structural
data that the code owns entirely and never deserialises (``ProjectLayout``, ``StageLayout``) uses
``dataclasses.dataclass(frozen=True)`` for simplicity and immutability without validation overhead.

**Template engine.** The writers layer uses Jinja2 rather than Python 3.13 t-strings. Jinja2 is
preferred because templates live on disk as ``.j2`` files (editable without touching Python
source), support ``{% if %}`` and ``{% for %}`` blocks required by conditional restraint sections
and replica loops, and provide whitespace control via ``{%- -%}`` trim markers. T-strings are
suitable for narrow, safety-critical inline interpolation tasks but are not a replacement for a
file-based templating system.

Examples
--------
Typical usage from a CLI command handler:

>>> from mdscaffold.core.project.config import ProjectConfig
>>> from mdscaffold.core.project.layout import ProjectLayout, default_stages
>>> from mdscaffold.core.project.scaffold import scaffold_project
>>>
>>> config = ProjectConfig.from_toml(project_dir)
>>> layout = ProjectLayout(
...     root=config.root,
...     replica_count=config.n_replicas,
...     n_prod_runs=config.simulation.n_prod_runs,
...     stages=default_stages(),
... )
>>> scaffold_project(layout)
"""
